### ISSUE TITLE
output example.

### ISSUE THREAD

**Issue by davidarroyo1234** [wladimir-computin/CC1101-ESP-Arduino#1]
Hi, nice work!

But could you provide some minimal example to write/output throught the cc1101 please.

**Comment by wischbgr** [comment]
Fixed in  #5696d074b48ea0fa0d8a7b0c7ee762f77092da5d :)

**Comment by wischbgr** [comment]
[https://github.com/wladimir-computin/CC1101-ESP-Arduino/blob/master/examples/Simple_Sender/Simple_Sender.ino](https://github.com/wladimir-computin/CC1101-ESP-Arduino/blob/master/examples/Simple_Sender/Simple_Sender.ino)

**Comment by davidarroyo1234** [comment]
> Fixed in  #5696d074b48ea0fa0d8a7b0c7ee762f77092da5d :)

Thanks!!
