### ISSUE TITLE
Need #include <climits> in CC1101_ESP_Arduino.cpp

### ISSUE THREAD

**Issue by raythefourth** [wladimir-computin/CC1101-ESP-Arduino#2]
I'm running this on ESP8266, specifically the Adafruit Feather Huzzah ESP8266. When compiling, I got an error "INT_MAX" not defined. The arduino IDE suggested I add **#include \<climits>** in CC1101_ESP_Arduino.cpp, which worked.

**Comment by MrColoo** [comment]
Same problem here

**Comment by wischbgr** [comment]
Thanks for that, I added the include!
