### ISSUE TITLE
need to add ICACHE_RAM_ATTR to ISR function for ESP8266

### ISSUE THREAD

**Issue by raythefourth** [wladimir-computin/CC1101-ESP-Arduino#3]
I'm running the Listen_and_print.ino script on ESP8266, specifically the Adafruit Feather Huzzah ESP8266. When running the script, it would crash unless I commented out the attachInterrupt() line. For the ESP8266, I have to add ICACHE_RAM_ATTR before the ISR function.

So for Listen_and_print.ino line 18 was:
void radioHandlerOnChange() {
and should be:
ICACHE_RAM_ATTR void radioHandlerOnChange() {

**Comment by wischbgr** [comment]
Thanks, nice catch!

I actually never tested any of this on ESP8266, just ESP32.

Fixed in #929c413d03790dcac0e86e0eda5776fe3edb78f1
