### ISSUE TITLE
CC1011-ESP-Arduino works well with ESP32C3 Super Mini & NewRemoteSwitch library

### ISSUE THREAD

**Issue by Lesateq** [wladimir-computin/CC1101-ESP-Arduino#6]
Hello Techfriends,

I have stumbled around with ESP32C3 Super Mini and SPI. I found out this is not easy, it is actually a nighmare. But thanks to the great peace of work at the CC1011-ESP-Arduino library it worked with a very little investment in time ! I would like to thank the author of this code. I also got it working to control RC Switches, in my case Klikaanklikout aka Trust Smart. I use the CC1101 connected to the ESP32C3 Super Mini. Next, I use the NewRemoteSwitch library (https://github.com/1technophile/NewRemoteSwitch) to control the RC switches.  In the Arduino IDE I selected board "ESP32C3 Dev Module" See code below for my SPI pinout:
`
//https://github.com/wladimir-computin/CC1101-ESP-Arduino
#include <CC1101_ESP_Arduino.h>

//https://github.com/wladimir-computin/espBitBanger
#include <EspBitBanger.h>

//https://github.com/1technophile/NewRemoteSwitch
#include <NewRemoteTransmitter.h>

#define REMOTE_RB        31212571
#define REMOTE_BB40     27612442
#define TXPIN       3     // TX pin on CC1101 = GDO0 connected to ESP32-C3 Super Mini pin 3
#define RXPIN       2     // RX pin on CC1101 = GDO2 connected to ESP32-C3 Super Mini pin 2

//ESP32 PINs
const int SPI_SCK = 4; 			//board or mcu specific
const int SPI_MISO = 5; 			//board or mcu specific
const int SPI_MOSI = 6; 			//board or mcu specific
const int SPI_CS = 7; 				//select any pin
const int RADIO_INPUT_PIN = 3; 	//select any pin, this is the TX-PIN
const int RADIO_OUTPUT_PIN = 2; 	//select any pin, this is the RX-PIN

EspBitBanger bitBanger;
CC1101 cc1101(SPI_SCK, SPI_MISO, SPI_MOSI, SPI_CS, RADIO_INPUT_PIN, RADIO_OUTPUT_PIN);
NewRemoteTransmitter transmitter(REMOTE_BB40 , TXPIN, 260, 3);

uint8_t buffer[] = {0b11101110, 0b10001110, 0b10001000, 0b10001110, 0b11101110, 0b10001000, 0b10001000, 0b10001000, 0b10001000, 0b11101110, 0b10001110, 0b10001110, 0b10000000};

void setup(){
	Serial.begin(19200);
	bitBanger.begin(2666, -1, RADIO_INPUT_PIN);
	cc1101.init();
	Serial.printf("CC1101: 0x%02x, version: 0x%02x\n", cc1101.getPartnum(), cc1101.getVersion());
	cc1101.setMHZ(433.92);
	cc1101.setTXPwr(TX_PLUS_10_DBM);
	cc1101.setDataRate(10000);
	cc1101.setModulation(ASK_OOK);
 
}

void loop(){
	while(true){
    Serial.printf("CC1101: 0x%02x, version: 0x%02x\n", cc1101.getPartnum(), cc1101.getVersion());
    cc1101.setTx();
    Serial.println("Sending CC1101 data");
    transmitter.sendUnit(0, true);
    delay(2000);
    transmitter.sendUnit(0, false);
    delay(2000);
    cc1101.setIdle();
  }
}
`

**Comment by wischbgr** [comment]
Hi @Lesateq ,

It seems, like you don't need EspBitBanger in your code, as you are using [/NewRemoteSwitch](https://github.com/1technophile/NewRemoteSwitch) for the actual bit banging. Other than that, nicely done :)
